### PR TITLE
Implemented mouser specific class and changed digikey specific keys in data to generic ones

### PR DESCRIPTION
**Pull request by twam**

### CODE REVIEW

**Comment by claudyus** [comment]
thanks @twam for your valuable contrib!

**Comment by twam** [comment]
You're welcome! Your reverse-engineering of the Digikey barcode will save me quite some time for my part database project :)

**Comment by claudyus** [comment]
Good! I was not sure that this work could be useful to some one mainly because I discovered that a lot of my digikey components are not indexed by google so this work was almost useless for me.
Did you are planning to use this project with a specific part inventory software?

**Comment by twam** [comment]
Yes. I want to write a small python tool to track all my stuff from Digikey/Mouser/... and be able to scan the bags I have with a barcode reader. You can find it at https://github.com/twam/partdb but I just started :)

**Pull request merged**
